### ISSUE TITLE
一定期間経つとPR環境を削除する

### ISSUE THREAD

**Issue by Goryudyuma** [dev-hato/hato-atama#31]

**Comment by massongit** [comment]
PRをマージしたらそのPR内の環境は削除する、というのもあり？

**Comment by Goryudyuma** [comment]
ありだけど、判定難しそう

**Comment by massongit** [comment]
バージョンにPRの番号を含めるというのはどうだろう？ (例: PR `#31`  の環境は `v31-1`, `v31-2`, ...)

**Comment by Goryudyuma** [comment]
一個前の環境を取ってくるのが面倒そう

**Comment by massongit** [comment]
やっぱり期間でやる方が楽か。

**Comment by massongit** [comment]
https://cloud.google.com/appengine/pricing?hl=ja
>基本または自動スケーリング: 課金はインスタンスが最後のリクエストを処理してから 15 分後に終了します

とのことなので、PR環境を削除しなくてもそこまで料金はかからないのかも。

**Comment by massongit** [comment]
PRのcloseやmasterへのpush起点で不必要な環境を削除するようにしたのでclose。
